### PR TITLE
[RFC] Redesign Commands Layout

### PR DESCRIPTION
**Pull request by BluePhoenixGame**
**Introduction**
Looking over Wilfred I noticed the use of cogs, for one single command....
So why not *actually* make it a command really?

What I am proposing is the following "template":
```python
class Name(commands.Command):

    def __init__(self):
        self.name = 'name'  # I forgot to put this in the examples  ( commit )

    async def callback(self, ctx):
        await ctx.send(ctx.author.name)

def setup(client):
    client.add_command(Name())
```
**Pros/Cons**
- In my opinion, this just makes more sense and *feels* better. But I am a little weird :/

- The obvious con with doing this, is the hacky way that one might think this gets implemented. Though I think this allows for better control.

- I don't know how serious memory usage and performance is taken, but I am pretty sure this will aid a lot. As we remove one layer of abstraction with cogs.

**Summary**
In the end, you can take a look at yourself of what would be needed to migrate to this below. I already changed some of the commands.
Though I have yet to determine how subcommands would be done, either they also become their own class and we do some fun in their init + set up. Or they are also methods of the Group class and we do some work in that init.
*I haven't gotten the bot set up, so my changes below is completely untested. But mostly for show anyways*

### CODE REVIEW

**Comment by volcanicer** [comment]
I feel like the current way of doing it is _fine_ (I'm against the general structure of the cogs folder, personally I believe they should be grouped into specific files like `!xp` and `!eco` being in a `manager.py` file but other developers feel differently and that's fine). I think before submitting a PR however, these changes should be tested and an example of integrating subcommands would be great, especially for `!crates` which uses them.

If you can get past the barrier of subcommands and make a working, clean and efficient implementation, I think it'll make a lot more sense than making a cog for every command. The basic idea of cogs in general in discord.py are to group your commands and listeners, which isn't the implementation presently in Wilfred.

**Comment by BluePhoenixGame** [comment]
> I feel like the current way of doing it is _fine_ (I'm against the general structure of the cogs folder, personally I believe they should be grouped into specific files like `!xp` and `!eco` being in a `manager.py` file but other developers feel differently and that's fine).

I completely agree with this,

> I think before submitting a PR however, these changes should be tested and an example of integrating subcommands would be great, especially for `!crates` which uses them.

I specifically made this a draft to be more open for discussion, while I can show changes and still work on it.

> If you can get past the barrier of subcommands and make a working, clean and efficient implementation, I think it'll make a lot more sense than making a cog for every command.

I'll continue working a bit more then. I only did a bit to showcase the idea of it all to get it kind of approved.

> The basic idea of cogs in general in discord.py are to group your commands and listeners, which isn't the implementation presently in Wilfred.

Exactly! Which is why I presented this. Since I assume it's a deliberate design choice to not group them together like that, so instead of having a rather empty cog just take the final step and make it a special command.

**Comment by volcanicer** [comment]
Perhaps I'm doing it wrong, but I've attempted to test this format with my own bot using the following code in a `randomcommand.py` file:
```from discord.ext import commands

class RandomCommand(commands.Command):
    def __init__(self):
        self.name = 'test'

    async def callback(self, ctx):
        await ctx.send("Hello World")

def setup(bot):
    bot.add_command(RandomCommand())```

However this doesn't work with the following error occurring:
`cogs.randomcommand could not be loaded: 'RandomCommand' object has no attribute 'module'`

**Comment by BluePhoenixGame** [comment]
**I have now transitioned and migrated the rest of the commands**
This is how I decided to do subcommands:
```python
class Name(commands.Group):

    def __init__(self):
        self.name = "name"

    async def callback(self, ctx):
        await ctx.send(ctx.author.name)


class NameSet(commands.Command):

    def __init__(self, parent):
        self.parent =parent
        self.name = "set"

    async def callback(self, ctx, name):
        await ctx.send("You can't change your own name silly :P")


def setup(client):
    name = Name()
    client.add_command(name)

   name.add_command(NameSet(name))
```
If preferred it should also be possible to have one command group and have functions inside that, which will be added to the list of commands, done inside the init.

I am going to attempt further and more extensive testing now, as I am not sure how happy discord.py is about all of this. Especially since we're not calling `super().__init__()`, what may need to be done is create an altered Command class that we inherit from.

**Comment by BluePhoenixGame** [comment]
> However this doesn't work with the following error occurring:
> `cogs.randomcommand could not be loaded: 'RandomCommand' object has no attribute 'module'`

This appears to be an issue with us overriding the `callback` property, it appears discord.py does some stuff inside the setter:
```python
    @property
    def callback(self):
        return self._callback

    @callback.setter
    def callback(self, function):
        self._callback = function
        self.module = function.__module__

        signature = inspect.signature(function)
        self.params = signature.parameters.copy()

        # PEP-563 allows postponing evaluation of annotations with a __future__
        # import. When postponed, Parameter.annotation will be a string and must
        # be replaced with the real value for the converters to work later on
        for key, value in self.params.items():
            if isinstance(value.annotation, str):
                self.params[key] = value = value.replace(annotation=eval(value.annotation, function.__globals__))

            # fail early for when someone passes an unparameterized Greedy type
            if value.annotation is converters.Greedy:
                raise TypeError('Unparameterized Greedy[...] is disallowed in signature.')
```
The `self.module` is later used inside converters to check if they are from the library itself. Also yes discord.py was not fully satisfied with us not calling init, understandably. So I am going to write a bit of a middle class, what this will do is simply move the code above from the setter into init.

There is actually no reason discord.py does this in a setter, except for one important ( in their case ) use-case: Help command.
You can see the callback getting changed here:
```python
    async def prepare(self, ctx):
        self._injected = injected = self._original.copy()
        injected.context = ctx
        self.callback = injected.command_callback

        on_error = injected.on_help_command_error
        if not hasattr(on_error, '__help_command_not_overriden__'):
            if self.cog is not None:
                self.on_error = self._on_error_cog_implementation
            else:
                self.on_error = on_error

        await super().prepare(ctx)
```
This is the **only** place where it wouldn't work to have that setter code inside init, and wilfred doesn't even use the dynamic HelpCommand, nor will ever changing to HelpCommand in the future disrupt anything we're changing with this pull request.

**Comment by MM-coder** [comment]
This entire thing seems pretty "hacky", I don't agree with the 1 command per cog model. But this suggested implementation isn't the solution to it. You are simply making it a `commands.Command` for the sake of readability with no significant benefits, performance or otherwise.

Currently the having each command as a cog system has many drawbacks but it does have the advantage of allowing moderators to quickly disable and enable commands by unloading and loading the respective cogs, if I'm not mistaken (haven't touched discord.py for a while, so feel free to correct me if I'm wrong) `commands.Command` has this terrible disabled implementation which only allows you to set said disabled status in the command's decorator, and not during runtime.

**Comment by volcanicer** [comment]
> if I'm not mistaken (haven't touched discord.py for a while, so feel free to correct me if I'm wrong) commands.Command has this terrible disabled implementation which only allows you to set said disabled status in the command's decorator, and not during runtime.

You can disable a command like:
```py
cmd = bot.get_command("command")
cmd.enabled = False

# Command Implementation
@bot.command()
async def disable(ctx, command: str):
    cmd = bot.get_command(command)
    cmd.enabled = False
```

**Comment by MM-coder** [comment]
> > if I'm not mistaken (haven't touched discord.py for a while, so feel free to correct me if I'm wrong) `commands.Command` has this terrible disabled implementation which only allows you to set said disabled status in the command's decorator, and not during runtime.
> 
> You can disable a command like:
> ```py
> cmd = bot.get_command("command")
> cmd.enabled = False
> 
> # Command Implementation
> @bot.command()
> async def disable(ctx, command: str):
>     cmd = bot.get_command(command)
>     cmd.enabled = False
> ```

Ah, so just edit the classes' property, fair enough. I still don't think this justifies the proposed changes.

This all seems very hacky, the overriding of the callback, and honestly I don't see the point to this. It is not like it's going to speed up the execution, or even make it easier to work with the code base (actually in my opinion it makes it unnecessarily more complex).

But that's just my two cents.

**Comment by BluePhoenixGame** [comment]
So I discussed this with some of the people in the discord.py server, and I think we're all just blinded by the idea of a command needing to be inside a cog...
This is embarrassingly simple...

We can just move it all out of everything....

From the original one-cog implementation:
```python
class Kitten(commands.Cog):

    def __init__(self, client):
        self.client = client

    @commands.command()
    async def kitten(self, ctx):
        imgUrl = requests.get('https://api.thecatapi.com/v1/images/search').json()[0]['url']
        em = discord.Embed(title="Kitten", image=imgUrl, colour=colour.secondary)
        em.set_image(url=imgUrl)
        await ctx.send(embed=em)

def setup(client):
    client.add_cog(Kitten(client))
```
To just moving it out of everything:
```python
@commands.command()
async def kitten(self, ctx):
    imgUrl = requests.get('https://api.thecatapi.com/v1/images/search').json()[0]['url']
    em = discord.Embed(title="Kitten", image=imgUrl, colour=colour.secondary)
    em.set_image(url=imgUrl)
    await ctx.send(embed=em)

def setup(client):
    client.add_command(kitten)
```

**Comment by BluePhoenixGame** [comment]
Bruh.... I thought I could force push without closing

**Comment by MM-coder** [comment]
> So I discussed this with some of the people in the discord.py server, and I think we're all just blinded by the idea of a command needing to be inside a cog...
> This is embarrassingly simple...
> 
> We can just move it all out of everything....
> 
> From the original one-cog implementation:
> 
> ```python
> class Kitten(commands.Cog):
> 
>     def __init__(self, client):
>         self.client = client
> 
>     @commands.command()
>     async def kitten(self, ctx):
>         imgUrl = requests.get('https://api.thecatapi.com/v1/images/search').json()[0]['url']
>         em = discord.Embed(title="Kitten", image=imgUrl, colour=colour.secondary)
>         em.set_image(url=imgUrl)
>         await ctx.send(embed=em)
> 
> def setup(client):
>     client.add_cog(Kitten(client))
> ```
> 
> To just moving it out of everything:
> 
> ```python
> @commands.command()
> async def kitten(self, ctx):
>     imgUrl = requests.get('https://api.thecatapi.com/v1/images/search').json()[0]['url']
>     em = discord.Embed(title="Kitten", image=imgUrl, colour=colour.secondary)
>     em.set_image(url=imgUrl)
>     await ctx.send(embed=em)
> 
> def setup(client):
>     client.add_command(kitten)
> ```

Sort of defeats the objective of having 1 command per cog, even though I don't know the objective of it. Might as well not do anything in this case, isn't really solving any of the issues the bot has, basically just changing things for the sake of changing things.

**Pull request closed without merging**
